// <auto-generated />
namespace Pedidos.Migrations.PedidosDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FueraDeLista : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FueraDeLista));
        
        string IMigrationMetadata.Id
        {
            get { return "201605100346077_FueraDeLista"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
