// <auto-generated />
namespace Pedidos.Migrations.PedidosDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ArchivosAdjuntos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ArchivosAdjuntos));
        
        string IMigrationMetadata.Id
        {
            get { return "201606140316220_ArchivosAdjuntos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
